# Generated by Django 4.2.7 on 2023-11-05 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
